-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 17 2024 15:30
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Account_Manager'   
-- AccountManagerID :  
-- Name            :  
-- Email           :  
-- Phone           :  
-- Department      :  
--
CREATE TABLE Account_Manager (
    AccountManagerID NUMBER(38) NOT NULL,
    Name             VARCHAR2(255) NOT NULL,
    Email            VARCHAR2(255) NOT NULL,
    Phone            VARCHAR2(20) NOT NULL,
    Department       VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_Account_Manager PRIMARY KEY (AccountManagerID)
)
/

--
-- Create Table    : 'Product'   
-- ProductID       :  
-- Name            :  
-- Category        :  
-- Price           :  
-- Description     :  
-- InventoryCount  :  
--
CREATE TABLE Product (
    ProductID      NUMBER(38) NOT NULL,
    Name           VARCHAR2(255) NOT NULL,
    Category       VARCHAR2(255) NOT NULL,
    Price          NUMBER(10, 2) NOT NULL,
    Description    VARCHAR2(4000) NOT NULL,
    InventoryCount NUMBER(38) NOT NULL,
    CONSTRAINT pk_Product PRIMARY KEY (ProductID)
)
/

--
-- Create Table    : 'Customer'   
-- CustomerID      :  
-- Name            :  
-- ContactNumber   :  
-- Email           :  
-- Address         :  
-- IndustryType    :  
-- AccountManagerID :  (references Account_Manager.AccountManagerID)
--
CREATE TABLE Customer (
    CustomerID       NUMBER(38) NOT NULL,
    Name             VARCHAR2(255) NOT NULL,
    ContactNumber    VARCHAR2(20) NOT NULL,
    Email            VARCHAR2(255) NOT NULL,
    Address          VARCHAR2(4000) NOT NULL,
    IndustryType     VARCHAR2(255) NOT NULL,
    AccountManagerID NUMBER(38) NOT NULL,
    CONSTRAINT pk_Customer PRIMARY KEY (CustomerID),
    CONSTRAINT fk_Customer FOREIGN KEY (AccountManagerID)
        REFERENCES Account_Manager (AccountManagerID)
        ON DELETE CASCADE
)
/

--
-- Create Table    : 'Order_'   
-- OrderID         :  
-- OrderDate       :  
-- DeliveryDate    :  
-- Status          :  
-- TotalAmount     :  
-- CustomerID      :  (references Customer.CustomerID)
--
CREATE TABLE Order_ (
    OrderID        NUMBER(38) NOT NULL,
    OrderDate      DATE NOT NULL,
    DeliveryDate   DATE NOT NULL,
    Status         VARCHAR2(50) NOT NULL,
    TotalAmount    NUMBER(10, 2) NOT NULL,
    CustomerID     NUMBER(38),
    CONSTRAINT pk_Order_ PRIMARY KEY (OrderID),
    CONSTRAINT fk_Order_ FOREIGN KEY (CustomerID)
        REFERENCES Customer (CustomerID)
)
/

--
-- Create Table    : 'Payment'   
-- PaymentID       :  
-- PaymentDate     :  
-- PaymentMethod   :  
-- Amount          :  
-- TransactionID   :  
-- OrderID         :  (references Order_.OrderID)
--
CREATE TABLE Payment (
    PaymentID      NUMBER(38) NOT NULL,
    PaymentDate    DATE NOT NULL,
    PaymentMethod  VARCHAR2(50) NOT NULL,
    Amount         NUMBER(10, 2) NOT NULL,
    TransactionID  VARCHAR2(50) NOT NULL,
    OrderID        NUMBER(38),
    CONSTRAINT pk_Payment PRIMARY KEY (PaymentID),
    CONSTRAINT fk_Payment FOREIGN KEY (OrderID)
        REFERENCES Order_ (OrderID)
)
/

--
-- Create Table    : 'Support_Ticket'   
-- TicketID        :  
-- IssueDescription :  
-- Status          :  
-- CreatedDate     :  
-- ResolvedDate    :  
-- CustomerID      :  (references Customer.CustomerID)
-- AccountManagerID :  (references Account_Manager.AccountManagerID)
--
CREATE TABLE Support_Ticket (
    TicketID          NUMBER(38) NOT NULL,
    IssueDescription  VARCHAR2(4000) NOT NULL,
    Status            VARCHAR2(50) NOT NULL,
    CreatedDate       DATE NOT NULL,
    ResolvedDate      DATE,
    CustomerID        NUMBER(38),
    AccountManagerID  NUMBER(38),
    CONSTRAINT pk_Support_Ticket PRIMARY KEY (TicketID),
    CONSTRAINT fk_Support_Ticket FOREIGN KEY (CustomerID)
        REFERENCES Customer (CustomerID),
    CONSTRAINT fk_Support_Ticket2 FOREIGN KEY (AccountManagerID)
        REFERENCES Account_Manager (AccountManagerID)
)
/

--
-- Create Table    : 'part_of'   
-- OrderID         :  (references Order_.OrderID)
-- ProductID       :  (references Product.ProductID)
--
CREATE TABLE part_of (
    OrderID    NUMBER(38) NOT NULL,
    ProductID  NUMBER(38) NOT NULL,
    CONSTRAINT pk_part_of PRIMARY KEY (OrderID, ProductID),
    CONSTRAINT fk_part_of FOREIGN KEY (OrderID)
        REFERENCES Order_ (OrderID)
        ON DELETE CASCADE,
    CONSTRAINT fk_part_of2 FOREIGN KEY (ProductID)
        REFERENCES Product (ProductID)
)
/

--
-- Permissions for: 'public'
--
GRANT ALL ON Account_Manager TO public
/
GRANT ALL ON Product TO public
/
GRANT ALL ON Customer TO public
/
GRANT ALL ON Order_ TO public
/
GRANT ALL ON Payment TO public
/
GRANT ALL ON Support_Ticket TO public
/
GRANT ALL ON part_of TO public
/

exit;
