SELECT P.*
FROM Product P
WHERE P.CATEGORY = 'Defense Systems'
ORDER BY P.PRODUCTID ASC;

UPDATE PRODUCT
SET Price = Price * 1.10
WHERE PRODUCT.CATEGORY = 'Defense Systems';
COMMIT;

SELECT P.*
FROM Product P
WHERE P.CATEGORY = 'Defense Systems'
ORDER BY P.PRODUCTID ASC;

ROLLBACK;

SELECT P.*
FROM Product P
WHERE P.CATEGORY = 'Defense Systems'
ORDER BY P.PRODUCTID ASC;
