insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYS.PART_OF (ORDERID, PRODUCTID)
values ((SELECT * FROM (SELECT ORDERID FROM AIR_ORDER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT PRODUCTID FROM PRODUCT ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

commit;

